version: 2
jobs:
  make_packages:
    resource_class: x-large
    steps:
      - checkout

      - run:
          name: ls
          command: |
            ls -lah packages

      - run:
          name: make packages
          command: docker-compose -f build/docker-compose.yaml run -e MAKEJOBS=8 prb-packages

      - run:
          name: ls
          command: |
            ls -lah packages

workflows:
  version: 2
  packages:
    jobs:
      - make_packages:
          filters:
            branches:
              only: circle-ci
