version: 2
jobs:
  build_main_deb:
    resource_class: x-large
    steps:
      - checkout

      - run:
          name: ls
          command: |
            ls -lah packages

      - run:
          name: make packages
          command: docker-compose -f build/docker-compose.yaml run prb-packages

      - run:
          name: ls
          command: |
            ls -lah packages

workflows:
  version: 2
  build:
    jobs:
      - build_main_deb:
          branches:
            only: circle-ci
